# Sabbir Ahmed
# System Development in the Unix Environment (605.614)
# Makefile
# Root Makefile for the project

ROOT = $(CURDIR)
SRC = $(ROOT)/src
BIN = $(SRC)/bin
LIB = $(SRC)/lib

.PHONY: it install depend clean

it:
	# pass

install:
	# pass

depend:
	# pass

clean:
	# clean out cache and temporary files
	rm *.a *.o
