# Sabbir Ahmed
# System Development in the Unix Environment (605.614)
# Makefile
# Main Makefile for the project

CXX ?= $(which $CXX)

.PHONY: it install depend clean

it:
	# pass

install:
	# pass

depend:
	# pass
	$(CXX) -M -g -I ../../../include cent_convert.cpp fahr_convert.cpp > depend_list

clean:
	# clean out cache and temporary files
	@echo $(CURDIR)
